### ISSUE TITLE
Color is not dart:ui color.

### ISSUE THREAD

**Issue by ljanecek** [vdakalov/fff#5]
Is there any way how use your library function ColorParser for dart ui color? 

```
type 'Color' is not a subtype of type 'Color' where
Color is from package:fff/color.dart
Color is from dart:ui
```

Thank you for your work!

**Comment by vdakalov** [comment]
Hello, @ljanecek. I stop work with Dart long time ago. May be you have any ideas? Please, feel free for send merge request

**Comment by ljanecek** [comment]
Ok @vdakalov, i can try something and you will see.
